### ISSUE TITLE
Handle multi-column foreign keys

### ISSUE THREAD

**Issue by codingconcepts** [codingconcepts/dgs#2]
Create table

```sql
CREATE TABLE public.users (
  id UUID NOT NULL,
  city VARCHAR NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (city ASC, id ASC)
);

CREATE TABLE public.user_promo_codes (
  city VARCHAR NOT NULL,
  user_id UUID NOT NULL,
  code VARCHAR NOT NULL,
  CONSTRAINT user_promo_codes_pkey PRIMARY KEY (city ASC, user_id ASC, code ASC),
  CONSTRAINT user_promo_codes_city_user_id_fkey FOREIGN KEY (city, user_id) REFERENCES public.users(city, id)
);
```

Generate config and data

```sh
dgs gen config \
  --url "postgres://root@localhost:26257?sslmode=disable" \
  --schema public \
  --row-count users:1 \
  --row-count user_promo_codes:1 \
  > dgs.yaml

dgs gen data \
  --workers 1 \
  --batch 1 \
  --url "postgres://root@localhost:26257?sslmode=disable" \
  --config dgs.yaml
```

The resulting error:

> FTL error generating data: generating data: generate worker: writing rows: executing query: ERROR: multiple assignments to the same column "city" (SQLSTATE 42601)

Looking at the config, we see that dgs has screwed up the generation of ref columns for the user_promo_codes table:

```yaml
tables:
  - name: users
    rows: 1
    columns:
      - name: id
        value: ${uuid}
      - name: city
        range: string
        props:
          min: 1
          max: 255
  - name: user_promo_codes
    rows: 1
    columns:
      - name: city
        ref: users.city
      - name: city
        ref: users.id
      - name: user_id
        ref: users.city
      - name: user_id
        ref: users.id
      - name: code
        range: string
        props:
          min: 1
          max: 255
```
